import type { Day } from "../types";
import { teach, demo, exercise, quizMC, recall, checkpoint } from "./helpers";

export const day02: Day = {
  id: 2,
  title: "Strings and indexing",
  subtitle: "Strings are sequences of characters. Master indexing, slicing, and the string methods that show up in every interview.",
  estimatedTime: "50–65 min",
  goals: [
    "Index strings with <code>s[i]</code> and negative indexes",
    "Slice with <code>s[a:b]</code> and know the endpoint is exclusive",
    "Use key methods: <code>lower</code>, <code>upper</code>, <code>strip</code>, <code>split</code>, <code>join</code>, <code>replace</code>",
    "Format strings with f-strings",
    "Understand that strings are <strong>immutable</strong>",
  ],
  youWillBuild: "Palindrome check, vowel counter, reverse-words — the bread and butter of string interviews.",
  steps: [
    teach(
      "d2-intro",
      "<p>Strings feel simple until an interviewer asks &quot;reverse the words in this sentence in-place.&quot; Today we build the muscle memory for indexing, slicing, and the handful of methods you&apos;ll reach for constantly.</p>",
    ),
    teach(
      "d2-index",
      "<p>Python strings are zero-indexed:</p><pre><code>s = \"python\"\ns[0]   # 'p'\ns[1]   # 'y'\ns[-1]  # 'n'  (last character)\ns[-2]  # 'o'  (second to last)\nlen(s) # 6</code></pre><p>Negative indexes count from the end. <code>s[-1]</code> is a Python idiom you&apos;ll use every day.</p>",
    ),
    demo(
      "d2-index-demo",
      "<p>Run this, then change the string to your name and predict each output:</p>",
      's = "python"\nprint(s[0])\nprint(s[-1])\nprint(s[len(s) - 1])\nprint(s[2])',
    ),
    teach(
      "d2-slice",
      "<p><strong>Slicing</strong> — <code>s[start:end]</code> returns characters from <code>start</code> up to but <em>not including</em> <code>end</code>.</p><pre><code>s = \"python\"\ns[0:3]   # 'pyt'\ns[2:5]   # 'tho'\ns[:3]    # 'pyt'  (from start)\ns[3:]    # 'hon'  (to end)\ns[::-1]  # 'nohtyp'  (reversed!)</code></pre><p>The <code>s[::-1]</code> trick — step of -1 walks backwards — is how you reverse a string in one line.</p>",
    ),
    demo(
      "d2-slice-demo",
      "<p>Play with it. Try different slice ranges:</p>",
      's = "interview"\nprint(s[:5])\nprint(s[5:])\nprint(s[-4:])\nprint(s[::-1])\nprint(s[::2])   # every other character',
    ),
    quizMC(
      "d2-q-slice",
      "What does <code>\"hello\"[1:4]</code> return?",
      ["<code>&quot;hell&quot;</code>", "<code>&quot;ell&quot;</code>", "<code>&quot;ello&quot;</code>", "<code>&quot;el&quot;</code>"],
      1,
      "Indexes 1, 2, 3 — and index 4 is excluded (the endpoint is always exclusive). So you get <code>e</code>, <code>l</code>, <code>l</code>.",
    ),
    exercise(
      "d2-ex-reverse",
      "<p>Write <code>reverse(s)</code> that returns the string reversed.</p>",
      "def reverse(s):\n    # your code here\n    pass\n",
      "def reverse(s):\n    return s[::-1]\n",
      "<code>s[::-1]</code> is the one-liner. The three-part slice is <code>[start:end:step]</code>, and a step of <code>-1</code> walks the string backwards.",
      [
        { call: 'reverse("hello")', expected: "olleh" },
        { call: 'reverse("")', expected: "" },
        { call: 'reverse("a")', expected: "a" },
        { call: 'reverse("ab")', expected: "ba" },
      ],
      { fnName: "reverse" },
    ),
    teach(
      "d2-methods",
      "<p>The string methods you&apos;ll use in 90% of problems:</p><ul><li><code>s.lower()</code> / <code>s.upper()</code> — case conversion</li><li><code>s.strip()</code> — removes whitespace from both ends</li><li><code>s.split(&quot; &quot;)</code> — splits into a list: <code>&quot;a b c&quot;.split(&quot; &quot;) == [&quot;a&quot;, &quot;b&quot;, &quot;c&quot;]</code></li><li><code>&quot;,&quot;.join(lst)</code> — joins a list into a string with the separator</li><li><code>s.replace(&quot;a&quot;, &quot;b&quot;)</code> — replaces occurrences</li><li><code>s.count(&quot;x&quot;)</code> — counts occurrences</li><li><code>&quot;x&quot; in s</code> — boolean substring check</li></ul><p>Strings are <strong>immutable</strong> — these methods return <em>new</em> strings. <code>s.lower()</code> doesn&apos;t change <code>s</code>.</p>",
    ),
    demo(
      "d2-methods-demo",
      "<p>Watch the immutability — <code>s</code> doesn&apos;t change:</p>",
      's = "  Hello World  "\nprint(s.strip())\nprint(s.strip().lower())\nprint("Original:", repr(s))   # still has spaces\nprint("-".join(["a", "b", "c"]))\nprint("hello".count("l"))\nprint("py" in "python")',
    ),
    quizMC(
      "d2-q-immutable",
      "What happens when you write <code>s[0] = &quot;H&quot;</code>?",
      [
        "The first character of <code>s</code> changes to <code>&quot;H&quot;</code>",
        "Python raises a <code>TypeError</code>",
        "It silently does nothing",
        "It creates a new string",
      ],
      1,
      "Strings are immutable — you <em>can&apos;t</em> modify characters in place. To change a character, build a new string (e.g., with slicing and concatenation).",
    ),
    exercise(
      "d2-ex-palindrome",
      "<p><strong>Palindrome check.</strong> Write <code>is_palindrome(s)</code> that returns <code>True</code> if the string reads the same forwards and backwards.</p><p>For this version, case doesn&apos;t matter — treat <code>&quot;Aa&quot;</code> as a palindrome.</p>",
      "def is_palindrome(s):\n    # your code here\n    pass\n",
      "def is_palindrome(s):\n    s = s.lower()\n    return s == s[::-1]\n",
      "Lowercase it first, then compare to its reverse.",
      [
        { call: 'is_palindrome("racecar")', expected: true },
        { call: 'is_palindrome("hello")', expected: false },
        { call: 'is_palindrome("Aa")', expected: true },
        { call: 'is_palindrome("")', expected: true },
        { call: 'is_palindrome("a")', expected: true },
      ],
      { fnName: "is_palindrome" },
    ),
    teach(
      "d2-fstr",
      "<p><strong>f-strings</strong> — the modern way to format:</p><pre><code>name = \"Ada\"\nage = 37\nprint(f\"{name} is {age}\")\nprint(f\"{age * 2} is twice her age\")\nprint(f\"{name.upper()}\")\nprint(f\"pi ≈ {3.14159:.2f}\")  # 2 decimal places</code></pre><p>Anything inside <code>{}</code> is a Python expression. Use these instead of <code>%</code> formatting or <code>+</code> concatenation.</p>",
    ),
    exercise(
      "d2-ex-vowels",
      "<p>Write <code>count_vowels(s)</code> that returns how many vowels (<code>aeiou</code>, case-insensitive) are in the string.</p>",
      "def count_vowels(s):\n    # your code here\n    pass\n",
      'def count_vowels(s):\n    s = s.lower()\n    count = 0\n    for ch in s:\n        if ch in "aeiou":\n            count += 1\n    return count\n',
      "Lowercase the string. Loop over characters. Use <code>ch in &quot;aeiou&quot;</code> to check membership.",
      [
        { call: 'count_vowels("hello")', expected: 2 },
        { call: 'count_vowels("HELLO")', expected: 2 },
        { call: 'count_vowels("xyz")', expected: 0 },
        { call: 'count_vowels("")', expected: 0 },
        { call: 'count_vowels("aeiou")', expected: 5 },
      ],
      { fnName: "count_vowels" },
    ),
    checkpoint(
      "d2-cp",
      "Halfway there",
      "Indexing, slicing, and core methods — you have the tools. One more pattern to learn (<code>split</code> / <code>join</code>) and then you&apos;re at the test.",
    ),
    teach(
      "d2-split",
      "<p><code>split</code> and <code>join</code> are inverses:</p><pre><code>\"a b c\".split(\" \")     # [\"a\", \"b\", \"c\"]\n\" \".join([\"a\", \"b\", \"c\"])  # \"a b c\"</code></pre><p>This pattern — split, transform, join — reverses words, cleans whitespace, swaps delimiters, etc.</p>",
    ),
    exercise(
      "d2-ex-reverse-words",
      "<p><strong>LeetCode #557 classic.</strong> Write <code>reverse_words(s)</code> that reverses <em>each word</em> in a sentence, keeping word order.</p><p><code>reverse_words(&quot;hello world&quot;)</code> → <code>&quot;olleh dlrow&quot;</code>.</p><p>Assume words are separated by single spaces.</p>",
      "def reverse_words(s):\n    # your code here\n    pass\n",
      'def reverse_words(s):\n    words = s.split(" ")\n    reversed_words = [w[::-1] for w in words]\n    return " ".join(reversed_words)\n',
      "Split on space. Reverse each word with <code>[::-1]</code>. Join back with a space.",
      [
        { call: 'reverse_words("hello world")', expected: "olleh dlrow" },
        { call: 'reverse_words("a b c")', expected: "a b c" },
        { call: 'reverse_words("abc")', expected: "cba" },
        { call: 'reverse_words("")', expected: "" },
      ],
      { fnName: "reverse_words" },
    ),
    recall(
      "d2-recall",
      "Why does <code>s.lower()</code> not change the original string? What does it do instead?",
      "Strings are immutable — they can&apos;t be modified. <code>s.lower()</code> returns a <em>new</em> string with the lowercase version. To keep it, you reassign: <code>s = s.lower()</code>.",
    ),
    teach(
      "d2-wrap",
      "<p>Today&apos;s toolkit:</p><ul><li><code>s[i]</code>, <code>s[-1]</code>, <code>s[a:b]</code>, <code>s[::-1]</code></li><li><code>lower</code>, <code>upper</code>, <code>strip</code>, <code>split</code>, <code>join</code>, <code>replace</code>, <code>in</code></li><li>f-strings</li><li>Immutability — always reassign</li></ul><p>Final test time.</p>",
    ),
  ],
  finalTest: [
    quizMC(
      "d2-t-slice",
      "What does <code>&quot;python&quot;[-3:]</code> return?",
      ["<code>&quot;pyt&quot;</code>", "<code>&quot;hon&quot;</code>", "<code>&quot;tho&quot;</code>", "<code>&quot;python&quot;</code>"],
      1,
      "<code>-3</code> starts 3 from the end, to the end of the string. That&apos;s <code>&quot;hon&quot;</code>.",
    ),
    exercise(
      "d2-t-first-word",
      "<p>Write <code>first_word(s)</code> that returns the first word of a sentence (characters before the first space). If there&apos;s no space, return the whole string.</p>",
      "def first_word(s):\n    # your code here\n    pass\n",
      'def first_word(s):\n    return s.split(" ")[0]\n',
      "<code>s.split(&quot; &quot;)</code> returns a list; take <code>[0]</code>.",
      [
        { call: 'first_word("hello world")', expected: "hello" },
        { call: 'first_word("python")', expected: "python" },
        { call: 'first_word("")', expected: "" },
        { call: 'first_word("one two three")', expected: "one" },
      ],
      { fnName: "first_word" },
    ),
    quizMC(
      "d2-t-mut",
      "Which statement is <strong>false</strong>?",
      [
        "<code>s.upper()</code> returns a new string",
        "<code>&quot;x&quot; in &quot;fox&quot;</code> is <code>True</code>",
        "<code>s[0] = &quot;A&quot;</code> modifies <code>s</code>",
        "<code>len(&quot;&quot;)</code> is <code>0</code>",
      ],
      2,
      "Strings are immutable — you can&apos;t assign into them.",
    ),
    exercise(
      "d2-t-initials",
      "<p>Write <code>initials(name)</code> that returns a string of uppercase initials. <code>&quot;john fitzgerald kennedy&quot;</code> → <code>&quot;JFK&quot;</code>.</p><p>Assume words are separated by single spaces and non-empty.</p>",
      "def initials(name):\n    # your code here\n    pass\n",
      'def initials(name):\n    return "".join(w[0].upper() for w in name.split(" "))\n',
      "Split on space. Take the first character of each word. Uppercase. Join.",
      [
        { call: 'initials("john fitzgerald kennedy")', expected: "JFK" },
        { call: 'initials("ada lovelace")', expected: "AL" },
        { call: 'initials("guido")', expected: "G" },
      ],
      { fnName: "initials" },
    ),
    exercise(
      "d2-t-palindrome-strict",
      "<p>Write <code>is_palindrome_clean(s)</code> — case-insensitive, but also ignore any character that is not a letter or digit. <code>&quot;A man, a plan, a canal: Panama&quot;</code> should return <code>True</code>.</p>",
      "def is_palindrome_clean(s):\n    # your code here\n    pass\n",
      "def is_palindrome_clean(s):\n    cleaned = ''.join(ch for ch in s.lower() if ch.isalnum())\n    return cleaned == cleaned[::-1]\n",
      "Lowercase. Keep only alphanumeric characters (<code>ch.isalnum()</code>). Compare to reverse.",
      [
        { call: 'is_palindrome_clean("A man, a plan, a canal: Panama")', expected: true },
        { call: 'is_palindrome_clean("race a car")', expected: false },
        { call: 'is_palindrome_clean(" ")', expected: true },
        { call: 'is_palindrome_clean("")', expected: true },
      ],
      { fnName: "is_palindrome_clean" },
    ),
  ],
};
