import type { Day } from "../types";
import { teach, demo, exercise, quizMC, recall, checkpoint } from "./helpers";

export const day01: Day = {
  id: 1,
  title: "Python fundamentals",
  subtitle: "Variables, types, arithmetic, and your first if/else. The building blocks for everything.",
  estimatedTime: "60–75 min",
  goals: [
    "Create variables and understand Python&apos;s core types — <code>int</code>, <code>float</code>, <code>str</code>, <code>bool</code>",
    "Use arithmetic, comparison, and boolean operators confidently",
    "Write <code>if</code>/<code>elif</code>/<code>else</code> branches and read logical expressions",
    "Convert between types (<code>int()</code>, <code>str()</code>, <code>float()</code>) without surprises",
    "Read error messages and fix simple bugs",
  ],
  youWillBuild: "A handful of tiny programs and two LeetCode-style problems that use only what you learn today.",
  steps: [
    teach(
      "d1-intro",
      "<p>Welcome — I&apos;m your teacher for the next 14 days.</p><p>Today is all about Python&apos;s absolute basics: variables, types, math, comparisons, and decisions. These aren&apos;t glamorous but every harder thing you&apos;ll do later is built on them.</p><p>You won&apos;t just read — I&apos;ll ask you to type, try, and explain. That&apos;s the only way it sticks.</p>",
    ),
    teach(
      "d1-var-intro",
      "<p><strong>A variable is a name for a value.</strong> In Python you create one by assigning with <code>=</code>:</p><pre><code>age = 25\nname = \"Alice\"</code></pre><p>No type declaration, no <code>let</code> or <code>var</code>, no semicolons. Python figures out the type from the value.</p>",
    ),
    demo(
      "d1-var-demo",
      "<p>Try it — click Run. Then change <code>name</code> to your own name and run again:</p>",
      'name = "Alice"\nage = 25\nprint("Hello,", name)\nprint("You are", age, "years old")',
    ),
    teach(
      "d1-types",
      "<p>Python has four basic types you&apos;ll see constantly:</p><ul><li><code>int</code> — whole numbers: <code>42</code>, <code>-7</code></li><li><code>float</code> — decimals: <code>3.14</code>, <code>-0.5</code></li><li><code>str</code> — text in quotes: <code>\"hello\"</code> or <code>&apos;hello&apos;</code></li><li><code>bool</code> — <code>True</code> or <code>False</code> (capital T, capital F!)</li></ul><p>Use <code>type(x)</code> to ask Python what type a value is.</p>",
    ),
    demo(
      "d1-types-demo",
      "<p>Run this and notice what <code>type()</code> returns for each value:</p>",
      'print(type(42))\nprint(type(3.14))\nprint(type("hello"))\nprint(type(True))',
      "Those <class 'int'> lines are Python telling you which type each value is.",
    ),
    quizMC(
      "d1-q-type",
      "What is the type of the value <code>3.0</code> in Python?",
      ["<code>int</code>", "<code>float</code>", "<code>str</code>", "<code>double</code>"],
      1,
      "Any number with a decimal point is a <code>float</code>, even if the decimal part is zero. Python doesn&apos;t have <code>double</code> — <code>float</code> is 64-bit already.",
    ),
    exercise(
      "d1-ex-hello",
      "<p>Make <code>greet(name)</code> return the string <code>\"Hello, &lt;name&gt;!\"</code>.</p><p>For example, <code>greet(\"Alice\")</code> should return <code>\"Hello, Alice!\"</code>.</p>",
      "def greet(name):\n    # your code here\n    pass\n",
      'def greet(name):\n    return f"Hello, {name}!"\n',
      "Use an f-string: <code>f\"Hello, {name}!\"</code> plugs the variable directly into the string.",
      [
        { call: 'greet("Alice")', expected: "Hello, Alice!" },
        { call: 'greet("Bob")', expected: "Hello, Bob!" },
        { call: 'greet("")', expected: "Hello, !" },
      ],
      { fnName: "greet" },
    ),
    teach(
      "d1-arith",
      "<p>The arithmetic operators are mostly what you expect, with two that surprise people:</p><ul><li><code>+  -  *  /</code> — standard</li><li><code>//</code> — integer division (drops the remainder): <code>7 // 2 == 3</code></li><li><code>%</code> — modulo (remainder): <code>7 % 2 == 1</code></li><li><code>**</code> — exponent: <code>2 ** 10 == 1024</code></li></ul><p><code>%</code> shows up constantly in interviews for &quot;is this divisible by n?&quot;, &quot;is this even?&quot;, wrapping around arrays, etc.</p>",
    ),
    demo(
      "d1-arith-demo",
      "<p>Predict each line&apos;s output <em>before</em> running. Then run it:</p>",
      "print(7 / 2)      # float division\nprint(7 // 2)     # integer division\nprint(7 % 2)      # remainder\nprint(2 ** 10)    # 2 to the 10th\nprint(-7 // 2)    # rounds toward -infinity, not zero!",
    ),
    quizMC(
      "d1-q-mod",
      "What does <code>15 % 4</code> evaluate to?",
      ["<code>3</code>", "<code>3.75</code>", "<code>4</code>", "<code>11</code>"],
      0,
      "<code>15 / 4 = 3</code> with remainder <code>3</code>. <code>%</code> gives the remainder: <code>15 - (3 × 4) = 3</code>.",
    ),
    exercise(
      "d1-ex-even",
      "<p>Write <code>is_even(n)</code> that returns <code>True</code> if <code>n</code> is even, <code>False</code> otherwise.</p><p>Use <code>%</code>. A number is even when dividing by 2 leaves remainder 0.</p>",
      "def is_even(n):\n    # your code here\n    pass\n",
      "def is_even(n):\n    return n % 2 == 0\n",
      "<code>n % 2</code> is 0 for even, 1 for odd. Compare with <code>==</code> to get a bool.",
      [
        { call: "is_even(4)", expected: true },
        { call: "is_even(7)", expected: false },
        { call: "is_even(0)", expected: true },
        { call: "is_even(-3)", expected: false },
      ],
      { fnName: "is_even" },
    ),
    teach(
      "d1-compare",
      "<p>Comparison operators produce <code>bool</code> values:</p><ul><li><code>==</code> equal &nbsp;&nbsp; <code>!=</code> not equal</li><li><code>&lt;</code>  <code>&gt;</code>  <code>&lt;=</code>  <code>&gt;=</code></li></ul><p><strong>Careful:</strong> <code>=</code> is assignment; <code>==</code> is comparison. Mixing these up is the single most common beginner bug.</p>",
    ),
    teach(
      "d1-bool",
      "<p>Combine booleans with <code>and</code>, <code>or</code>, <code>not</code> — written as English words, not <code>&amp;&amp;</code> / <code>||</code> / <code>!</code>.</p><p>Python also lets you <em>chain</em> comparisons: <code>0 &lt;= x &lt; 10</code> reads like math and means &quot;x is in [0, 10)&quot;. This is unusual among languages and shows up on interview code.</p>",
    ),
    demo(
      "d1-bool-demo",
      "<p>Try it:</p>",
      'x = 5\nprint(x > 0 and x < 10)       # and\nprint(0 <= x < 10)            # chained — same thing\nprint(not (x == 5))           # not\nprint(x == 5 or x == 10)      # or',
    ),
    exercise(
      "d1-ex-grade",
      "<p>Write <code>grade(score)</code> that returns:</p><ul><li><code>\"A\"</code> if score is 90 or above</li><li><code>\"B\"</code> if 80–89</li><li><code>\"C\"</code> if 70–79</li><li><code>\"F\"</code> otherwise</li></ul>",
      "def grade(score):\n    # your code here\n    pass\n",
      'def grade(score):\n    if score >= 90:\n        return "A"\n    elif score >= 80:\n        return "B"\n    elif score >= 70:\n        return "C"\n    else:\n        return "F"\n',
      "Use <code>if</code> / <code>elif</code> / <code>else</code>. Check the highest threshold first and use <code>return</code> — once you return, the function exits, so you don&apos;t need to worry about overlapping ranges.",
      [
        { call: "grade(95)", expected: "A" },
        { call: "grade(90)", expected: "A" },
        { call: "grade(85)", expected: "B" },
        { call: "grade(72)", expected: "C" },
        { call: "grade(40)", expected: "F" },
        { call: "grade(0)", expected: "F" },
      ],
      { fnName: "grade" },
    ),
    teach(
      "d1-truthy",
      "<p>Python has a concept called <strong>truthiness</strong> — any value can be used where a boolean is expected.</p><p>These are <em>falsy</em> (treated as False): <code>0</code>, <code>0.0</code>, <code>\"\"</code> (empty string), <code>[]</code> (empty list), <code>{}</code> (empty dict), <code>None</code>, <code>False</code>.</p><p>Everything else is truthy.</p><p>So <code>if name:</code> is the idiomatic way to say &quot;if name is not empty&quot;.</p>",
    ),
    quizMC(
      "d1-q-truthy",
      "Which expression evaluates to <code>False</code>?",
      [
        "<code>bool(\"0\")</code>",
        "<code>bool(0)</code>",
        "<code>bool([0])</code>",
        "<code>bool(\"False\")</code>",
      ],
      1,
      "The number <code>0</code> is falsy. The string <code>\"0\"</code> is a non-empty string (truthy!), and the list <code>[0]</code> is non-empty (also truthy). Always ask &quot;is this empty/zero/None?&quot; — not &quot;does it look false?&quot;",
    ),
    teach(
      "d1-cast",
      "<p>Python doesn&apos;t auto-convert between <code>int</code> and <code>str</code>, so <code>&quot;5&quot; + 3</code> is a <code>TypeError</code>.</p><p>You convert explicitly:</p><ul><li><code>int(&quot;42&quot;)</code> → <code>42</code></li><li><code>str(42)</code> → <code>&quot;42&quot;</code></li><li><code>float(&quot;3.14&quot;)</code> → <code>3.14</code></li></ul><p>User input from <code>input()</code> is always a string — even if they type a number. You&apos;ll need to <code>int(...)</code> it.</p>",
    ),
    recall(
      "d1-recall-types",
      "<p>In your own words: when would Python give you a <code>TypeError</code>, and how do you fix it?</p>",
      "A TypeError typically happens when you use an operator on incompatible types — like <code>&quot;5&quot; + 3</code>, or <code>len(42)</code>. You fix it by explicitly converting the value with <code>int()</code>, <code>str()</code>, etc., so both sides are the same type.",
    ),
    checkpoint(
      "d1-cp-halfway",
      "You&apos;re halfway!",
      "Nice — variables, types, arithmetic, comparisons, booleans, and if/else are in your head now. The rest of the lesson is one more problem and then a short final test. Keep going — the second half of the lesson is where it starts clicking.",
    ),
    exercise(
      "d1-ex-fizz",
      "<p><strong>Mini LeetCode — FizzBuzz (classic).</strong></p><p>Write <code>fizzbuzz(n)</code> that returns a string based on <code>n</code>:</p><ul><li><code>\"FizzBuzz\"</code> if <code>n</code> is divisible by both 3 and 5</li><li><code>\"Fizz\"</code> if only by 3</li><li><code>\"Buzz\"</code> if only by 5</li><li>otherwise the number as a string</li></ul><p>This problem has been an interview filter for decades. The trick: check &quot;divisible by 15&quot; (both) <em>first</em>.</p>",
      "def fizzbuzz(n):\n    # your code here\n    pass\n",
      'def fizzbuzz(n):\n    if n % 15 == 0:\n        return "FizzBuzz"\n    if n % 3 == 0:\n        return "Fizz"\n    if n % 5 == 0:\n        return "Buzz"\n    return str(n)\n',
      "Check the most specific case (divisible by 15) first. Then 3, then 5, then the default. <code>return</code> exits the function, so no <code>elif</code> needed.",
      [
        { call: "fizzbuzz(15)", expected: "FizzBuzz" },
        { call: "fizzbuzz(9)", expected: "Fizz" },
        { call: "fizzbuzz(10)", expected: "Buzz" },
        { call: "fizzbuzz(7)", expected: "7" },
        { call: "fizzbuzz(30)", expected: "FizzBuzz" },
      ],
      { fnName: "fizzbuzz" },
    ),
    teach(
      "d1-wrap",
      "<p>That&apos;s all the ingredients for today. A quick recap in your head:</p><ul><li>Variables hold values. Python infers the type.</li><li><code>//</code> divides and drops remainder, <code>%</code> keeps it.</li><li><code>==</code> compares, <code>=</code> assigns.</li><li><code>and</code> / <code>or</code> / <code>not</code>, not <code>&amp;&amp;</code>.</li><li>Empty things are falsy.</li></ul><p>Ready for the final test? 5 quick questions — passing unlocks Day 2.</p>",
    ),
  ],
  finalTest: [
    quizMC(
      "d1-t-divmod",
      "What does <code>17 // 5</code> evaluate to?",
      ["<code>3.4</code>", "<code>3</code>", "<code>2</code>", "<code>3.0</code>"],
      1,
      "<code>//</code> is integer division and returns an <code>int</code> (no decimal).",
    ),
    quizMC(
      "d1-t-compare",
      "Which line has a bug?",
      [
        "<code>if x &gt;= 0 and x &lt;= 10:</code>",
        "<code>if 0 &lt;= x &lt;= 10:</code>",
        "<code>if x = 5:</code>",
        "<code>if x == 5 or x == 10:</code>",
      ],
      2,
      "<code>=</code> is assignment, not comparison. Inside <code>if</code> you need <code>==</code>.",
    ),
    exercise(
      "d1-t-abs",
      "<p>Write <code>my_abs(n)</code> that returns the absolute value of <code>n</code> without using the built-in <code>abs()</code>.</p>",
      "def my_abs(n):\n    # your code here\n    pass\n",
      "def my_abs(n):\n    if n < 0:\n        return -n\n    return n\n",
      "If <code>n</code> is negative, return <code>-n</code>; else return <code>n</code>.",
      [
        { call: "my_abs(5)", expected: 5 },
        { call: "my_abs(-5)", expected: 5 },
        { call: "my_abs(0)", expected: 0 },
      ],
      { fnName: "my_abs" },
    ),
    quizMC(
      "d1-t-truthy",
      "Which value is <em>truthy</em>?",
      ["<code>0</code>", "<code>&quot;&quot;</code>", "<code>&quot;False&quot;</code>", "<code>None</code>"],
      2,
      "<code>&quot;False&quot;</code> is a non-empty string, so it&apos;s truthy. Only <em>empty</em> strings are falsy.",
    ),
    exercise(
      "d1-t-max3",
      "<p>Write <code>max_of_three(a, b, c)</code> that returns the largest of three numbers. No <code>max()</code>.</p>",
      "def max_of_three(a, b, c):\n    # your code here\n    pass\n",
      "def max_of_three(a, b, c):\n    if a >= b and a >= c:\n        return a\n    if b >= c:\n        return b\n    return c\n",
      "Check if <code>a</code> beats both others; if not, compare <code>b</code> and <code>c</code>.",
      [
        { call: "max_of_three(1, 2, 3)", expected: 3 },
        { call: "max_of_three(10, 5, 7)", expected: 10 },
        { call: "max_of_three(-1, -5, -3)", expected: -1 },
        { call: "max_of_three(4, 4, 4)", expected: 4 },
      ],
      { fnName: "max_of_three" },
    ),
  ],
};
